### ISSUE TITLE
TIE/vn Silencer XWS

### ISSUE THREAD

**Issue by dbxau** [zacharyp/sb2xws#1]
Expected Behavior
XWS export should list TIE/vn Silencer ship as "tievnsilencer"

Actual Behavior
XWS exports TIE/vn Silencer ship as "tiesilencer"

Example:

// 20181217101812
// https://sb2xws.herokuapp.com/translate/fcf89768-8d27-4571-b10f-c20c91c598ae

{
  "faction": "firstorder",
  "pilots": [
    {
      "id": "kyloren",
      "ship": "tiesilencer",
      "upgrades": {
        "force": [
          "hate"
        ]
      },
      "points": 85
    }
  ],
  "name": "Squd name",
  "description": "",
  "points": 85
}

**Comment by zacharyp** [comment]
Fixed, reading from the xwing-data2 `xws` value now for each ship.
