### ISSUE TITLE
Force Power upgrade XWS

### ISSUE THREAD

**Issue by dbxau** [zacharyp/sb2xws#2]
Expected Behavior
XWS export should list Force Power upgrades as "force-power" (or "forcepower" ?)

Actual Behavior
XWS exports Force Power upgrades as "force"

Example:

// 20181217101812
// https://sb2xws.herokuapp.com/translate/fcf89768-8d27-4571-b10f-c20c91c598ae

{
  "faction": "firstorder",
  "pilots": [
    {
      "id": "kyloren",
      "ship": "tiesilencer",
      "upgrades": {
        "force": [
          "hate"
        ]
      },
      "points": 85
    }
  ],
  "name": "Squd name",
  "description": "",
  "points": 85
}

**Comment by zacharyp** [comment]
Changed to `force-power` 👍
