### ISSUE TITLE
Lists with Bombardment Drones do not translate

### ISSUE THREAD

**Issue by wedge1126** [zacharyp/sb2xws#3]
Any list with a Bombardment Drone will return a list without any pilots.

Example output: 
`{"faction":"separatistalliance","pilots":[],"name":"Attack of the Hyenas! M2","description":"","points":200,"vendor":{"sb2xws":{"builder":"SB2XWS","url":"http://sb2xws.herokuapp.com/translate/5896a972-27ce-437e-a336-12d498f5191f"}}}`

**Comment by zacharyp** [comment]
fixed now.  Thanks for the report.
